### ISSUE TITLE
document wiki

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#194] opened 2019-02-25 05:56 UTC
see /sandbox/code/github/threefoldtech/jumpscaleX/docs/tools/wiki

copy all content to do with openresty / wiki / markdown to this section
explain which JS tools are available

have tutorial here how to start an openresty & generate docs

explan the macros

**Comment by abom** [comment] 2019-03-11 20:10
Listing related docs of **wiki, markdowndocs tool, custom markdown and macros.**
Documents that needs to be copied/updated:

https://github.com/threefoldtech/jumpscaleX/tree/development/Jumpscale/tools/markdowndocs/readme.md
https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/tools/markdowndocs/macros/readme.md
https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/tools/markdowndocs/macros

Need to know if openresty docs that was written outside of this repo should be moved/copied too:
https://github.com/threefoldtech/digitalmeX/tree/development/docs/webserver
I think this one need to updated too.
https://github.com/threefoldtech/digitalmeX/tree/master/docs/publishing_platform

**Openresty and IYO**
https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/builder/web/docs/resty_iyo.md

The new way of doc templates/handlebars need to be documented (or copied if already exists), like this file (also, the javascript library need to be copied to _jumpscale_weblibs_):
https://github.com/threefoldfoundation/www_threefold_lapis/blob/master/docs/footer/footer.md



Will update this list if new docs found.

**Comment by arahmanhamdy** [comment] 2019-03-14 11:40
please add section for serving wikis using docsify

**Comment by abom** [comment] 2019-03-17 13:26
Added more docs about docsites at the front-end (docsite.js) in https://github.com/threefoldtech/jumpscaleX/pull/218/commits/9dec030ca9455c06201005b9b4d7c6d5d06f77ae

**Comment by abom** [comment] 2019-03-17 13:30
Added [docsite.js](https://github.com/threefoldtech/jumpscale_weblibs/blob/master/static/docsites/docsite.js) (copy of `lapis_client.js` from [www_threefold_lapis](https://github.com/threefoldfoundation/www_threefold_lapis)) to [jumpscale_weblibs](https://github.com/threefoldtech/jumpscale_weblibs), so anyone can use it (see previous comment for documentation).

**Comment by abom** [comment] 2019-03-17 14:41
Documentation can be found [here](https://github.com/threefoldtech/jumpscaleX/blob/ddc8c5da91f0002d6f60db9e90c6f56c5a95fd15/docs/tools/wiki/README.md).

**Comment by abom** [comment] 2019-04-17 14:43
@arahmanhamdy Do we need this anymore?

**Comment by rkhamis** [comment] 2019-04-23 09:00
duplicate of https://github.com/threefoldtech/digitalmeX/issues/42.

Done and verified

**Closed as completed by rkhamis** 2019-04-23 09:00 UTC
