### ISSUE TITLE
Docker option in installation does not work

### ISSUE THREAD

**Issue by serboctor** [threefoldtecharchive/jumpscaleX_archived#336] opened 2019-04-11 10:28 UTC
https://github.com/threefoldtech/jumpscaleX/blob/master/docs/Installation/install.md

Using the installation guide `python3 /tmp/install.py -3 -y -c` fails. I didn't dig deeper, but it seems that even if you're using the `development` branch, it still clones `development_type` inside the docker even though I can see in the code that the default branch is `development`.

**Comment by waleedhammam** [comment] 2019-04-11 14:23
it works now.
#### steps made to check it's working on my system
```
- su
- mkdir -p /home/waleedhammam/code/github/threefoldtech
- cd /home/waleedhammam/code/github/threefoldtech
- git clone git@github.com:threefoldtech/jumpscaleX.git
- cd jumpscaleX
- git checkout development
- git pull
- rm -f /tmp/install.py
- rm -f /tmp/InstallTools.py
- ln -s /home/waleedhammam/code/github/threefoldtech/jumpscaleX/install/install.py /tmp/install.py
- ln -s /home/waleedhammam/code/github/threefoldtech/jumpscaleX/install/InstallTools.py /tmp/InstallTools.py
- service ssh start
- ssh-add -L
- python3 /tmp/install.py -3 -y -c
```
#### also tried on a remote machine with
```
- curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX/development/install/install.py?$RANDOM > /tmp/install.py;
- python3 /tmp/install.py -3 -y -c
```

**Comment by serboctor** [comment] 2019-04-11 16:02
It turns out that regardless of the branch and repo location you link the installer from on your host, it clones the repos needed in /root/code/. And apparently I already had repos cloned there but they were checked out on `development_types`. It seems that if the installer finds the repos, it doesnt checkout the correct branch.

**Comment by waleedhammam** [comment] 2019-04-11 16:06
OK, will check it

**Comment by waleedhammam** [comment] 2019-04-14 08:12
working on ubuntu docker installer

**Comment by waleedhammam** [comment] 2019-04-15 10:24
Changelog:  https://github.com/threefoldtech/jumpscaleX/commit/fc1272281bb3f9f62cb35791c202dd258ceade6d
- [Fix] install docker with a specified branch. -default: 'development'-
- [Fix] install docker with a code exists under installation path.

**Comment by waleedhammam** [comment] 2019-04-15 15:21
Changelog: https://github.com/threefoldtech/jumpscaleX/commit/5652544448e5a7bd3ad95ce96e43a452f82afc80

- [Fix] add branch checker to avoid checkout if installation branch is the current one, to avoid uncommitted changes loss

**Comment by AhmedHanafy725** [comment] 2019-04-16 10:38
### There are two scenarios:
#### 1- No jumpscaleX found under installation dir:
- Will clone jsx with selected branch (default: development) and install from it.
#### 2- jumpscaleX found under installation dir:
- Install from same branch: 
   - Will install jsx from existing code.
- Install from other branch:
   - Will stash the existing code, checkout to selected branch, update it to latest commit then install from it.

**Comment by AhmedHanafy725** [comment] 2019-04-16 10:43
Verified

**Comment by hossnys** [comment] 2019-04-23 08:29
the installer with option in docker and with all other options consider that pip3 is already installed and didn't install it neither in install.py nor InstallTools.py
```
stderr:
    /tmp/jumpscale/scripts/46033.sh: line 4: pip3: command not found

CANNOT CONTINUE
```

**Comment by hossnys** [comment] 2019-04-23 11:09
can't reproduce it , so i'll close it again , will open it if i found this error again

**Closed as completed by hossnys** 2019-04-23 11:09 UTC
Labels: priority_critical
