### ISSUE TITLE
Create a client for 0-stor daemon

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#680] opened 2019-07-03 13:37 UTC
In order to finish https://github.com/threefoldtech/home/issues/343
We need to integrate the 0-stor daemon python client into JSx.

The python client is available at: https://github.com/threefoldtech/0-stor/tree/master/daemon/client/py-client

**Comment by despiegk** [comment] 2019-08-18 08:31
needs to be proper JSX client

**Comment by muhamadazmy** [comment] 2019-08-18 10:48
Duplicate of #577

**Comment by ranatrk** [comment] 2019-08-20 14:58
- Created a clone of the python client files in zstor in jsx zstor client directory
- Added a wrapper using jsx configuration to use the zstor client
https://github.com/threefoldtech/jumpscaleX/commit/978990afe3c20cda471d0f10f942fcbc1c1b79e7

Accessible through `j.clients.zstor` and takes the following params: 
- __name__ : name of the client instance to be created
- __ip__ : IP address of the daemon running
- __port__ : adddress port of the daemon running

**Comment by Pishoy** [comment] 2019-08-22 10:23
verified
```
root@3bot:/# /root/go/bin/zstor -D --config aConfigFile.yaml daemon --listen 127.0.0.1:8000 
DEBU[0000] Debug logging enabled                        
INFO[0000] Version: 1.1.0-beta-3                        
INFO[0000] Daemon Server interface: grpc
```          
- in new session 
```
root@3bot:/# kosmos
JSX> j.servers.zdb.default.start()                                                                                                                                                                                                   
no server running on /tmp/tmux-0/default
no server running need to start
++ '[' start == kill ']'
++ tmux -f /sandbox/cfg/.tmux.conf has-session
no server running on /tmp/tmux-0/default
++ '[' 1 -eq 1 ']'
++ echo 'no server running need to start'
++ tmux -f /sandbox/cfg/.tmux.conf new -s main -d 'bash --rcfile /sandbox/bin/env_tmux_detach.sh'
++ '[' start '!=' start ']'
main: 1 windows (created Thu Aug 22 10:11:29 2019) [80x24]
JSX>                                                                                                                                                                                                                                 
JSX> zdb = j.clients.zstor.get("test",ip="127.0.0.1",port=8000)                                                                                                                                                                      
JSX> zdb.write_file('/sandbox/code/test.py')                                                                                                                                                                                         
[chunkSize: 65
objects {
  key: "\000\000\000\000"
  shardID: "127.0.0.1:9900"
}
hash: "XO\266\324\200\377D\227V\3163h\202\324}L(1\006}.\032\347\375\354L\321w\270h\006["
]

JSX> x = zdb.write_file('/sandbox/code/test.py')            

JSX> zdb.read(x)                                                                                                                                                                                                                     
b'just for test flis\n'
```
- js version 
```
3BOTDEVEL:3bot:jumpscaleX: git log -1
commit 9f1a4a8d397fdc8e4472bce86580a1739e38cfa6 (HEAD -> development_jumpscale, origin/development_jumpscale)
Author: kristof de spiegeleer <>
Date:   Thu Aug 22 10:00:06 2019 +0200

    BCDB fix (I think) for parent_id issue
```

**Closed as completed by Pishoy** 2019-08-22 10:23 UTC
Labels: state_verification, type_feature
