### ISSUE TITLE
j.clients/builder.influxdb

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#17] opened 2018-12-19 04:14 UTC
- config manager
- implement installer & basic test

**Comment by despiegk** [comment] 2018-12-19 04:15
split in 2 files: factory, instance

**Comment by despiegk** [comment] 2018-12-19 05:38
also implement j.builder....
look at readme in that builder directory & TEMPLATE dir

**Comment by despiegk** [comment] 2018-12-19 05:55
- implement j.client
    - [learn how to do it in template for client](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/clients/TEMPLATE)   
- implement j.builder....
    - [learn how to do it in template](https://github.com/threefoldtech/jumpscale10/tree/master/Jumpscale/builders/TEMPLATE)

**Comment by waleedhammam** [comment] 2019-05-26 10:03
Duplicate of #522

**Comment by waleedhammam** [comment] 2019-05-27 07:58
Implemented Build, Install. Still on the rest of the builder

**Comment by waleedhammam** [comment] 2019-05-27 13:42
**Refactored builder at: https://github.com/threefoldtech/jumpscaleX/commit/963828c9e433aaaf33216ba1d2e2ffda2915dc0f**
* Implemented Build, Install, Sandbox, Start, Stop, Test

**Comment by Dina-Abd-Elrahman** [comment] 2019-06-04 10:04
- build, install, start, stop, snadbox and test are working fine

**Closed as completed by Dina-Abd-Elrahman** 2019-06-04 10:04 UTC
