### ISSUE TITLE
docker support working again

### ISSUE THREAD

**Issue by despiegk** [threefoldtecharchive/jumpscaleX_archived#305] opened 2019-04-03 07:21 UTC
/sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/tools/docker/Docker.py

need to be tested & fixed where required

**Comment by serboctor** [comment] 2019-05-23 08:00
Depends on #501 and #468

**Comment by serboctor** [comment] 2019-05-23 08:58
Duplicate of #468

**Closed as completed by serboctor** 2019-05-23 08:58 UTC
